fix the failed of create_index_acl (#58)
The following case in postgresSQL will be ok, But GPDB does not allow executing non-SELECT statement on QEs.
this case will throw an error, and can not achieve the test objectives as postgresSQL does. This needs to be commented out.

CREATE UNIQUE INDEX u2rows ON s.x USING btree
((s.index_this_expr(y, s.const())) COLLATE s.coll s.citext_pattern_ops)
WHERE s.index_row_if(y);

ERROR: function cannot execute on a QE slice because it issues a non-SELECT statement (seg1 127.0.1.1:8003 pid=186596)
CONTEXT: SQL function "setter" during startup
SQL function "const" statement 1