Put `ESCAPE 'OFF'` verbatim into pg_exttable.fmtopts
The empty string doesn't work here. Fixes

    ERROR:  escape must be a single character, or [OFF/off] to disable escapes

on segments.

This reverts commit 443bfa4c73f543afe65e2d80b410ee1eaed3da15.