Fix case that a Var is used in RANGE BETWEEN.
If the Var was not used anywhere else, you got:

ERROR:  variable not found in subplan target list

This makes the 'qp_olap_windowerr' test pass.