Fix compiler warning ‘src_minmxid’ may be used uninitialized.
With gcc (GCC) 6.2.0, it produces the warning

     In file included from dbcommands.c:22:0:
     dbcommands.c: In function ‘createdb’:
     ../../../src/include/postgres.h:387:71: error: ‘src_minmxid’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     static inline Datum TransactionIdGetDatum(TransactionId tid) { return (Datum) tid; }
     	                                                                      ^~~~~~~~~~~
     dbcommands.c:123:14: note: ‘src_minmxid’ was declared here
     MultiXactId src_minmxid;
              ^~~~~~~~~~~
	cc1: some warnings being treated as errors

Not seeing this with 7.3 but for CI need to fix it.