Fix FOR SHARE / FOR UPDATE, at least in simple cases.
There are two lines of attack in the same commit:

1. Fix handling of the new LockRows plan type. Add walker/mutator,
   serialization, etc.

2. Don't create a LockRows node for distributed tables. In GPDB, any
   updates on a distributed table grabs an ExclusiveLock, which locks out
   all other processes. Therefore, you don't need tuple-level locks. (We
   didn't acquire them before this merge either.)

FIXME:

There are still this issue, if you have distributed plan, with LockRows
nodes:

postgres=# create table foo (id int4) distributed by (id);
CREATE TABLE
postgres=# select * from foo, pg_class for update;
ERROR:  no parameter found for initplan subquery (cdbsubplan.c:285)