On second thoughs, better to not try to "justify" the resgroup wait time.
Looking closer at the old implementation, I believe it didn't justify
either. And the user can call 'justify_interval' if that's what she wants.

The reason I'm second-guessing commit f9881030a6 is that it didn't compile:

resgroup.c: In function ‘ResGroupGetStat’:
resgroup.c:1024:73: error: ‘MSECS_PER_SECOND’ undeclared (first use in this function); did you mean ‘USECS_PER_SEC’?
    interval->month = ms_left / ((int64) DAYS_PER_MONTH * SECS_PER_DAY * MSECS_PER_SECOND);
                                                                         ^~~~~~~~~~~~~~~~
                                                                         USECS_PER_SEC