Fix errors caused by missed cache invalidation.
In qp_dml_joins test:

begin;
SELECT COUNT(*) FROM dml_ao_pt_r;
 count
-------
   100
(1 row)

ALTER TABLE dml_ao_pt_r ADD DEFAULT partition def;
INSERT INTO dml_ao_pt_r values(generate_series(1,10),NULL,'text');
ERROR:  expected partdefid 113359, but got 0 (partdesc.c:176)

The problem here is that the SELECT query created two gangs, the
primary writer gang, and also one reader gang. The reader gang
loads the partitioning information into the relcache, and the
obsolete information was still there after the ALTER TABLE. To
fix, destroy any idle QE backends at ALTER TABLE.

It's a bit surprising that we haven't seen this with any other
ALTER TABLE commands before. I think in principle, this could
happened with many other ALTER TABLE commands.