When deducing implicit partition bounds, process DEFAULT partition last.
Otherwise, the logic that peeks into previous or next partition will get
confused by the DEFAULT partition between other partitions.

Fixes this failure in 'qp_misc_jiras' test:

create table qp_misc_jiras.tbl5028_part_test (a int, b date,c text)
partition by range(b)
(
	partition p1 start('2007-01-01'),
        partition p2 start('2008-01-01'),
        partition p3 start('2009-01-01'),
	default partition def_part
);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  TO must specify exactly one value per partitioning column