BitmapIndexScan: re-add the ScanInfo serialization routines
These were missed in commit fd66ab32783. This fixes the

    ERROR:  could not deserialize unrecognized node type:

messages in ICW, but exposes a crash caused by code that assumes that
IndexScan and BitmapIndexScan are the same.

Signed-off-by: Tom Meyer <tmeyer@pivotal.io>