Fix looking up the WindowAgg's first ORDER BY column, for RANGE BETWEEN.
Was causing this failure in 'window' test:

SELECT sum(unique1) over (order by four range between 2::int8 preceding and 1::int2 preceding),
	unique1, four
FROM tenk1 WHERE unique1 < 10;
ERROR:  could not find comparison function for ordering operator 0 (nodeWindowAgg.c:2418)