Fix error from missing flow on append plans.
E.g. from 'partition1' test:

postgres# select * from ggg order by 1, 2;
ERROR:  Unexpected internal error (cdbllize.c:958)