Avoid error if AO relation size is needed before building AUX rels.
This was happening during partition creation, in 'partition_storage' test:

alter table pt_heap_tab add partition jkl values ('jkl','jkl1','jkl2') WITH (appendonly=true); -- AO
DETAIL:  This can be validly caused by a concurrent delete operation on this object.
ERROR:  could not open relation with OID 0

AOCS tables don't have the same problem, because the corresponding
aoco_relation_size() function uses GetAllAOCSFileSegInfo(), which already
had this special case for missing AO segrel.