Fix error on AO/AOCO table before AUX tables are created, again.
This was done earlier already in commit d31189c08, but it was lost in
commit 40977cc3c3. Fix it again in the same way.

Per this failure from 'partition_storage' test:

    alter table pt_heap_tab add partition xyz values ('xyz','xyz1','xyz2') WITH (appendonly=true, orientation=column, compresslevel=5); -- CO
    ERROR:  could not open relation with OID 0
    DETAIL:  This can be validly caused by a concurrent delete operation on this object.