Attempt to silence compiler warnings on some Ubuntu systems.
In the concourse pipeline, the Ubuntu build was failing with errors like
this:

varlena.c: In function 'text_position':
varlena.c:1253:36: error: 'state.skiptablemask' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     hptr += state->skiptable[*hptr & skiptablemask];
                              ~~~~~~^~~~~~~~~~~~~~~
varlena.c:994:20: note: 'state.skiptablemask' was declared here
  TextPositionState state;
                    ^~~~~
varlena.c:1239:9: error: 'state.wstr2' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      if (nptr == needle)
         ^
varlena.c:994:20: note: 'state.wstr2' was declared here
  TextPositionState state;
                    ^~~~~
varlena.c:994:20: error: 'state.wstr1' may be used uninitialized in this function [-Werror=maybe-uninitialized]
varlena.c:1183:9: error: 'state.str2' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      if (nptr == needle)
         ^
varlena.c:994:20: note: 'state.str2' was declared here
  TextPositionState state;
                    ^~~~~
varlena.c:994:20: error: 'state.str1' may be used uninitialized in this function [-Werror=maybe-uninitialized]

I don't understand why the compiler used on that system doesn't see that
those fields are in fact initialized in the cases that they are used. The
code is identical to PostgreSQL's, and there haven't been any changes in
later PostgreSQL versions either, and I'm pretty sure we would've heard if
people were getting compiler warnings on common Ubuntu systems. But an
initialization is cheap, so let's just silence the warning and move on.