Remove check for NOT NULLable column from ORCA translation of INSERT values.
When creating an ORCA plan for "INSERT ... (<col list>) VALUES (<values>)"
statement, the ORCA translator performed NULL checks for any columns not
listed in the column list. Nothing wrong with that per se, but the error
message produced was slightly different from the one you get at execution
time. Remove the check from ORCA transaltor, and rely on the execution
time check, to get rid of the inconsistency.

It was also inconsistent, in how columns that were listed in the column
list, and columns that were not listed, were treated:

postgres=# create table notnulls (a text NOT NULL, b text NOT NULL);
CREATE TABLE
postgres=# insert into notnulls (a) values ('x');
ERROR:  null value in column "b" violates not-null constraint
postgres=# insert into notnulls (a,b) values ('x', NULL);
ERROR:  null value in column "b" violates not-null constraint  (seg2 127.0.0.1:40002 pid=26547)
DETAIL:  Failing row contains (x, null).

This became topical in the merge, because of commit 991f3e5ab3, which added
more information to the executor check.

NOTE: another good candidate for extracting to a separate PR.