Fix duplicate parse analysis transformation of partition spec in CREATE TABLE
Fixes error in create_table test:
CREATE TABLE partitioned (
	a int,
	b int,
	c text,
	d text
) PARTITION BY RANGE (a oid_ops, plusone(b), c collate "default", d collate "C");
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  unrecognized node type: 145 (parse_expr.c:399)  (seg2 127.0.0.1:40002 pid=25906) (parse_expr.c:399)