Cherry-pick upstream fix for bug triggered by 'qp_union_intesect' test.
Failure:

UPDATE dml_union_r SET d = 20000 WHERE a in (SELECT a FROM dml_union_r UNION ALL SELECT a FROM dml_union_s);
ERROR:  Unexpected internal error (tupleremap.c:500)
DETAIL:  FailedAssertion("!(typmod >= 0)", File: "tupleremap.c", Line: 500)

Upstream commit:

commit 7fc0f06221d22632daa3ff8b70919b43e8a242ca
Author: Tom Lane <tgl@sss.pgh.pa.us>
Date:   Fri Nov 20 20:38:12 2009 +0000

    Add a WHEN clause to CREATE TRIGGER, allowing a boolean expression to be
    checked to determine whether the trigger should be fired.

    For BEFORE triggers this is mostly a matter of spec compliance; but for AFTER
    triggers it can provide a noticeable performance improvement, since queuing of
    a deferred trigger event and re-fetching of the row(s) at end of statement can
    be short-circuited if the trigger does not need to be fired.

    Takahiro Itagaki, reviewed by KaiGai Kohei.